### ISSUE TITLE
Investigate why D delegate -> Lua fails under LDC now

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/lumars#10]
Most likely answer is that the ABI for functions is different now, need to spend some time in Godbolt to figure out what's gone on.

**Comment by LunaTheFoxgirl** [comment]
This is not an issue on my system, it may be because you're using an older version of LDC2.
Older versions of D were not ABI compatible with C fully, sending variables in the opposite order to the registers.

This is fixed in newer D versions which are ABI compatible with the cdecl calling convention.

**Comment by MC41Github** [comment]
I get the following error using ldc 1.30.0:
![Screenshot_2022-07-29_02-44-09](https://user-images.githubusercontent.com/25404214/181660291-e20d3a61-c76e-430c-9f5a-2c46e3b63dd8.png)
Here is some info about the ldc that I have installed:
![Screenshot_2022-07-29_02-47-14](https://user-images.githubusercontent.com/25404214/181660443-4cee7391-7045-4357-bcef-a864fb763019.png)

**Comment by LunaTheFoxgirl** [comment]
The reason you get that error is because of an intentional assert put there, you will have to remove it to avoid that error, like this  
![image](https://user-images.githubusercontent.com/7032834/181660773-c8321d7a-e340-4201-a7aa-b9a5074dd3c7.png)

**Comment by LunaTheFoxgirl** [comment]
```
PS F:\Projects\inochi\inochi-session> ldc2 --version
LDC - the LLVM D compiler (1.28.1):
  based on DMD v2.098.1 and LLVM 12.0.1
  built with LDC - the LLVM D compiler (1.28.1)
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver2
  http://dlang.org - http://wiki.dlang.org/LDC
```

Version I'm running

**Comment by BradleyChatha** [comment]
:eyes: That could definitely be the issue. In any case if it's fixed on the later versions I'll remove the assert and just tell people to upgrade if they run into any issues.

**Comment by BradleyChatha** [comment]
Version 1.4.1 removes this assert

**Comment by LunaTheFoxgirl** [comment]
It doesn't seem to have been published to dub, could you queue a dub update on the website?

**Comment by BradleyChatha** [comment]
Weird. Should be there now
