### ISSUE TITLE
Update bindbc-lua dependency to 0.5.0

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BradleyChatha/lumars#11]
By updating to 0.5.0 you'd stay up to date with the current changes happening in bindbc land as bindbc-loader has moved to 1.0.0.

**Comment by BradleyChatha** [comment]
Fixed by https://github.com/BradleyChatha/lumars/commit/4d4ffdf613d0ce58c37e394ca7b689bc1d5629e5
