### ISSUE TITLE
How to register or bind variadic function? Overloaded functions?

### ISSUE THREAD

**Issue by Domain** [BradleyChatha/lumars#13]
How to register or bind variadic function? Overloaded functions?

**Comment by BradleyChatha** [comment]
I'm not too sure how overloaded functions would work, considering Lua doesn't support them (I think).

However I variadic functions currently don't have any support. If I don't get round to implementing that today for you, it'll definitely be by the end of the week :)

**Comment by Domain** [comment]
Both sol2(C++) and xlua(C#) support overloaded functions.

**Comment by BradleyChatha** [comment]
Ahhh I see, yeah that'll be doable as well with a bit of work. Again, I'll try to get this done before end of week for you :)

**Comment by BradleyChatha** [comment]
Hey there, I've added support for these two things in the latest version (v1.5.0).

It might take some time for dub to pick up the new tag, but in any case let me know if this helps you out.

The README shows examples of how to use this new functionality
