### ISSUE TITLE
Add universal macOS binary support

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BradleyChatha/lumars#14]
While building macOS builds for Inochi Session it fails with errors due to builds not being universal (both for x86 and arm)
https://github.com/Inochi2D/inochi-session/actions/runs/3228163136/jobs/5283895489#step:7:1429

This should probably be fixed.

**Comment by BradleyChatha** [comment]
Hopefully fixed by 38436f9d806e0081f772cb843656fc494bd0239c

I don't have an Intel Mac to really test locally, and I'm too lazy atm the setup CICD properly, but hopefully that'll get you through. (Really bad answer, I know)

**Comment by BradleyChatha** [comment]
Tag is 1.6.1, which I'll go force dub to update to
