### ISSUE TITLE
How do I return multiple values from a function?

### ISSUE THREAD

**Issue by TheZipCreator** [BradleyChatha/lumars#16]
In lua you can do stuff like

```lua
function myFunc()
  return 1, 2;
end
```

how would I translate this to a native D function? translating a single return value makes sense but I'm not sure how you can do two

**Comment by BradleyChatha** [comment]
There's no easy way to do this right now.

However! I have some free time and implementing this would be really easy, so give me an hour and I should be able to get this feature written up and documented for you 😄

**Comment by BradleyChatha** [comment]
Fixed in ebd4918d48eb21ffb5f8724f3ed1421e21200e14

The README has some documentation on how to return multiple values.

You'll need to update your dub.json (maybe also dub.selections.json) to point to `v1.7.0`.

Any issues or questions please let me know 😁

**Comment by Domain** [comment]
Maybe we can use Tuple as the return type?

**Comment by BradleyChatha** [comment]
That could be interesting yeah. Honestly it was just a bit of a quick and dirty thing. I'll open a feature request for it.
