### ISSUE TITLE
Upgrade the prebuilt binaries for LuaJit to the latest version

### ISSUE THREAD

**Issue by Domain** [BradleyChatha/lumars#17]
I am not sure which version you bundled with. But I cannot use the latest extensions modules, such as table.clear. Replace with manual-built library works fine.

**Comment by BradleyChatha** [comment]
Odd, the deps were compiled from the LuaJIT repo.

... Though now I remember I did play around with reference Lua at some point on Windows, which might be whats in the repo. Are you on Windows by chance 😓 ?

Either way, I'll try to get it sorted soon!

**Comment by Domain** [comment]
Yes, I am on Windows.
