### ISSUE TITLE
[Feature Request] Show lua stacktrace on error

### ISSUE THREAD

**Issue by Domain** [BradleyChatha/lumars#18]
It will be very helpful to show the stacktrace instead of just throwing an exception.

**Comment by BradleyChatha** [comment]
I agree yeah. Will look into it soon since it shouldn't be that hard.

**Comment by BradleyChatha** [comment]
@Domain I've tagged v1.8.0 which fixes this and #19 

I'll work towards #17 at the end of the week, since I currently don't have access to my Linux machine (I've tried to get cross-compilation to work on my M1 Mac before, and it was... painful, so I'll wait until I can do it on Linux instead).
