### ISSUE TITLE
How do I create a dynamic library that can be require()d into Lua?

### ISSUE THREAD

**Issue by finnurthorisson** [BradleyChatha/lumars#42]
Great library! But I can't figure out how to make libraries for use in Lua

Giving a C example:

```c
// hello.c
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>

int luaopen_hello(lua_State* L){
	lua_pushstring(L, "Hello!");
	return 1;
}
```

```sh
[lumarstest] cc hello.c -shared -o hello.so
[lumarstest] lua -e 'local hello = require("hello") ; print(hello)'
Hello!
```

How can I create the equivalent `.so` with Lumars?

**Comment by BradleyChatha** [comment]
Hey! I've had a play around and here's the full set of steps:

1. Create a new dub project (`dub init hello`)
2. Add lumars as a dependency
3. In dub.json/dub.sdl, set `targetType` to be `dynamicLibrary` ([docs](https://dub.pm/dub-reference/build_settings/#targettype))
4. Use the provided code snippet for your `app.d` code.
5. Run `dub build`
6. Note: On Linux and maybe also Mac, the file will be called `libhello.so`, so you may need to change some names.
7. Run `lua -e 'local hello = require("hello") ; print(hello)'`
8. And hopefully everything should work fine for you :)

```d
import lumars     : luaCWrapperSmart, LuaState;
import bindbc.lua : lua_State;

extern(C) int luaopen_hello(lua_State* L) {
	return luaCWrapperSmart!hello(L);
}

string hello(LuaState* l, string param) {
	return "Param from require: "~param;
}

// On Windows we need to mixin a DllMain to properly setup DRuntime.
// I don't know if we need to do something like this on Linux as well, but you can always ask the forums for more help.
version(Windows)
{
	import core.sys.windows.windows;
	import core.sys.windows.dll;

	mixin SimpleDllMain;
}
```

I have no real experience with using D DLLs from non-D programs, so there might be some quirkiness to it (especially around GC memory), but as I mentioned in the code snippet, there's plenty of help on the forums or the D discord if you run into obscure issues.

**Comment by finnurthorisson** [comment]
It works! I wasn't aware of `luaCWrapperSmart` or that you could combine bindbc here. Thank you!

**Comment by FelipeLema** [comment]
this is not working for me, not sure how to debug
this is done using neovim's luajit, I get the following error when doing `require'hello'()` (using neovim's `:lua` command)
```D
auto hello(LuaState *l)
{
  auto t = LuaTable.new(l);
  t["abc"]=&luaCWrapperSmart!some_fun;
  return t;
}
```

```
E5108: Error executing lua Expected exactly 0 args, but was given 1.
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: at 0x7f70b516dc20
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```
