### ISSUE TITLE
Add support for both static and dynamic linking

### ISSUE THREAD

**Issue by BradleyChatha** [BradleyChatha/lumars#8]

**Comment by LunaTheFoxgirl** [comment]
Bumping this, quite needed for Inochi Session since we want to be able to drop in LuaJIT in the future

**Comment by BradleyChatha** [comment]
I'll get round to this on Saturday

**Comment by LunaTheFoxgirl** [comment]
Sounds good uwu

**Comment by BradleyChatha** [comment]
Not sure if you're on Windows or not, but I don't have a machine to test that Windows is working. But otherwise it's working on Mac (M1... except not under DMD for some strange reason) and under Linux
