### ISSUE TITLE
Support executing scripts in different environments

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [BradleyChatha/lumars#9]
In my game engine entities can have scripts which are instantiated on the fly. I wish to switch my implementation over to Lumars to simplify some of the process.

One part that would help would be a way to set a pcall's up value to a table, in other words changing the table the global environment is in. This would allow lua chunks to dump in functions to tables directly. Allowing for runtime creation of types.
Of course the ideal solution here is to use metatables in conjunction with the upvalue.

Example:
```c
luaL_loadfile(L, "test.lua");
lua_getglobal(L, "testenv");
lua_setupvalue(L, -2, 1);

// contents of test.lua is put in the testenv global table
lua_pcall(L, 0, 0, 0);
```

Being able to do this with arbitrary tables would be nice.

**Comment by BradleyChatha** [comment]
I think I see what you mean, do you mean being able to do something like this?

```d
auto table = state.globalTable.get!LuaTable("testenv")
state.loadFile("test.lua", table); // Replaces _G with 'table' only for the scope of 'test.lua'
```

**Comment by LunaTheFoxgirl** [comment]
Yes, bonus if the library eventually supports compiling and loading byte code.
